[debug]
google_redirection_url = "http://localhost:8000/api/auth/google/connect"
google_client_id_uri = "./static/secrets/google_client_id"
google_client_secret_uri = "./static/secrets/google_client_secret"
aws_client_id_uri = "./static/secrets/aws_client_id"
aws_client_secret_uri = "./static/secrets/aws_client_secret"
rocket_secret_key_uri = "./static/secrets/rocket_secret_key"

[release]
google_redirection_url = "https://spotmee.co/api/auth/google/connect"
google_client_id_uri = "./static/secrets/google_client_id"
google_client_secret_uri = "./static/secrets/google_client_secret"
aws_client_id_uri = "./static/secrets/aws_client_id"
aws_client_secret_uri = "./static/secrets/aws_client_secret"
rocket_secret_key_uri = "./static/secrets/rocket_secret_key"